[project]
name = "whitelabel"
authors = [
    { name = "Bhavesh Maheshwari", email = "maheshwaribhavesh95863@gmail.com" },
]
description = "Whitelabel"
requires-python = ">=3.10"
readme = "README.md"
dynamic = ["version"]

[build-system]
requires = ["flit_core >=3.4,<4"]
build-backend = "flit_core.buildapi"

[tool.ruff]
line-length = 110
target-version = "py310"
